### ISSUE TITLE
unable to install on Julia 1.1

### ISSUE THREAD

**Issue by mikehui** [cortner/PyAMG.jl#14]
ERROR: Unsatisfiable requirements detected for package PyAMG [80c87078]:
 PyAMG [80c87078] log:
 ├─possible versions are: [0.0.1-0.0.9, 0.1.1, 0.2.0-0.2.1] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.9, 0.1.1, 0.2.0-0.2.1]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

I am using julia 1.1

**Comment by cortner** [comment]
I've released a new version, which might resolve this for you once it is registered. But I no longer maintain PyAMG. I recommend using `AMG.jl` or otherwise `clone` instead of `add` this repository.  You are welcome to make PRs to fix compatibility issues.

**Comment by cortner** [comment]
this should be fixed with v0.3.1 - please reopen this issue if not
