### ISSUE TITLE
output convergence history

### ISSUE THREAD

**Issue by git4lei** [cortner/PyAMG.jl#4]
Dear Christoph,

Is there a way to read the statistics of the solver, such as convergence history, etc? I looked at ?solve, but has no clue so far.

Best regards,
Lei

**Comment by cortner** [comment]
Can you look at the pyamg docs? If they have an option then we can get it. Otherwise we you can use PyAmg.jl as a preconditioner with IterativeSolvers.jl and extract the iteration info from there.

**Comment by cortner** [comment]
I looked a bit into `pyamg`. I didn't find what you wanted, but the following might help: 
```
A, b = L2d(100)
x, S = PyAMG.solve(A, b; return_solver=true)
```
`S` is now a `PyObject` wrapping an instance of `pyamg.multilevel.multilevel_solver`, which is the solver that was used to solve your problem. If you print it then it will display some diagnostics. Probably there is a way to extract the convergence history.

**Comment by git4lei** [comment]
Hi Christoph, thanks for look into this, I have found a demo code, 
https://github.com/pyamg/pyamg-examples/blob/master/Preconditioning/demo.py
which can extract the convergence history with the following code.

import scipy
import numpy
from pyamg.gallery import linear_elasticity, poisson
from pyamg import smoothed_aggregation_solver, rootnode_solver

A,B = poisson((500,500), format='csr'), None
method = smoothed_aggregation_solver
mls = method(A, B=B)
b = scipy.rand(A.shape[0],1)
standalone_residuals = []
mls.solve(b, tol=1e-10, residuals=standalone_residuals)
standalone_residuals  = numpy.array(standalone_residuals)/standalone_residuals[0]  

name = "Poisson"
# Plot convergence history
import pylab
pylab.figure()
pylab.title('Convergence History (%s)' % name)
pylab.xlabel('Iteration')
pylab.ylabel('Relative Residual')
pylab.semilogy(standalone_residuals,  label='Standalone',  linestyle='None', marker='.')
pylab.legend()
pylab.show()

**Comment by cortner** [comment]
thank you - I'll add this to the package when I have time.

**Comment by cortner** [comment]
So this is strange: 
```
N = 100
L1 = spdiagm((-ones(N-1), 2*ones(N), -ones(N-1)), (-1,0,1), N, N) * N^2
A = kron(speye(N), L1) + kron(L1, speye(N))
b = ones(size(A,1))
import PyAMG
residuals = []
Amg = PyAMG.SmoothedAggregationSolver(A)
x = PyAMG.solve(Amg, b, residuals=residuals)
```
yields the error
```
ERROR: PyError (:PyObject_Call) <type 'exceptions.AttributeError'>
AttributeError("'numpy.ndarray' object has no attribute 'append'",)
  File "/Users/ortner/anaconda/lib/python2.7/site-packages/pyamg/multilevel.py", line 455, in solve
    residuals.append(residual_norm(A, x, b))

 in pyerr_check at /Users/ortner/.julia/v0.5/PyCall/src/exception.jl:56 [inlined]
 in pyerr_check at /Users/ortner/.julia/v0.5/PyCall/src/exception.jl:61 [inlined]
 in macro expansion at /Users/ortner/.julia/v0.5/PyCall/src/exception.jl:81 [inlined]
 in #_pycall#62(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /Users/ortner/.julia/v0.5/PyCall/src/PyCall.jl:551
 in (::PyCall.#kw##_pycall)(::Array{Any,1}, ::PyCall.#_pycall, ::PyCall.PyObject, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at ./<missing>:0
 in #pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /Users/ortner/.julia/v0.5/PyCall/src/PyCall.jl:568
 in (::PyCall.#kw##pycall)(::Array{Any,1}, ::PyCall.#pycall, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at ./<missing>:0
 in #call#67(::Array{Any,1}, ::PyCall.PyObject, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /Users/ortner/.julia/v0.5/PyCall/src/PyCall.jl:571
 in (::PyCall.#kw#PyObject)(::Array{Any,1}, ::PyCall.PyObject, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at ./<missing>:0
 in #solve#5(::Array{Any,1}, ::Function, ::PyAMG.AMGSolver{PyAMG.SmoothedAggregation}, ::Array{Float64,1}) at /Users/ortner/.julia/v0.5/PyAMG/src/PyAMG.jl:145
 in (::PyAMG.#kw##solve)(::Array{Any,1}, ::PyAMG.#solve, ::PyAMG.AMGSolver{PyAMG.SmoothedAggregation}, ::Array{Float64,1}) at ./<missing>:0
```
I have no idea what is going on here, since `ndarray` definitely does have `append` defined.

**Comment by git4lei** [comment]
I got no error when I run your code, but residuals is 0-element Array{Any,1}.

**Comment by cortner** [comment]
It works if you use PyArray. I'll fix the interface and let you know

**Comment by cortner** [comment]
Could you please pull the latest master and test whether it works for you now? (note I've added some documentation on this to the readme)

**Comment by git4lei** [comment]
I used Pkg.update() to update to the latest version, then tried the code in your readme, 

N = 100
L1 = spdiagm((-ones(N-1), 2*ones(N), -ones(N-1)), (-1,0,1), N, N) * N^2
A = kron(speye(N), L1) + kron(L1, speye(N))
b = ones(size(A,1))
amg = RugeStubenSolver(A)
r = Float64[]
x = PyAMG.solve(amg, b, residuals=r)

I got the following error, 

ERROR: PyError (:PyObject_Call) <type 'exceptions.AttributeError'>
AttributeError("'numpy.ndarray' object has no attribute 'append'",)
  File "/Users/work/anaconda/lib/python2.7/site-packages/pyamg/multilevel.py", line 450, in solve
    residuals.append(residual_norm(A, x, b))

 in pyerr_check at /Users/work/.julia/v0.5/PyCall/src/exception.jl:56 [inlined]
 in pyerr_check at /Users/work/.julia/v0.5/PyCall/src/exception.jl:61 [inlined]
 in macro expansion at /Users/work/.julia/v0.5/PyCall/src/exception.jl:81 [inlined]
 in #_pycall#62(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /Users/work/.julia/v0.5/PyCall/src/PyCall.jl:551
 in (::PyCall.#kw##_pycall)(::Array{Any,1}, ::PyCall.#_pycall, ::PyCall.PyObject, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at ./<missing>:0
 in #pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /Users/work/.julia/v0.5/PyCall/src/PyCall.jl:568
 in (::PyCall.#kw##pycall)(::Array{Any,1}, ::PyCall.#pycall, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at ./<missing>:0
 in #call#67(::Array{Any,1}, ::PyCall.PyObject, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at /Users/work/.julia/v0.5/PyCall/src/PyCall.jl:571
 in (::PyCall.#kw#PyObject)(::Array{Any,1}, ::PyCall.PyObject, ::Array{Float64,1}, ::Vararg{Array{Float64,1},N}) at ./<missing>:0
 in #solve#5(::Array{Any,1}, ::Function, ::PyAMG.AMGSolver{PyAMG.RugeStuben}, ::Array{Float64,1}) at /Users/work/.julia/v0.5/PyAMG/src/PyAMG.jl:145
 in (::PyAMG.#kw##solve)(::Array{Any,1}, ::PyAMG.#solve, ::PyAMG.AMGSolver{PyAMG.RugeStuben}, ::Array{Float64,1}) at ./<missing>:0

If I used 
r=[]
then I didn't get any error, but r is 0-element Array{Any,1}.

**Comment by cortner** [comment]
To pull the latest master use
'Pkg.checkout("PyAMG")'

**Comment by git4lei** [comment]
Thanks, it works now!

**Comment by cortner** [comment]
great, then I'll close this, and tag a new release. In 2-3 days' time you can probably do `Pkg.free("PyAMG")` to go back on the latest release rather than master
