### ISSUE TITLE
Solve arguments as type information?

### ISSUE THREAD

**Issue by ChrisRackauckas** [cortner/PyAMG.jl#7]
It would be nice to be able to set the arguments for solve as the type information, so that way `\` will solve with a certain tolerance and things like that.

**Comment by cortner** [comment]
makes sense. I'll try to do that asap.

**Comment by cortner** [comment]
Turns out I had already implemented that for `solve`, but not for `\`. Can you pull master and check whether this is what you want? 

You can set the `kwargs` using `set_kwargs!`; or during construction, via `RugeStubenSolver(A::SparseMatrixCSC, kwargs...)`

**Comment by ChrisRackauckas** [comment]
Looks good.
